language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: "j/54ygAcqZMDYFKPRTEQxuiu0beehe8wCV4EN+iNKHRWKJ+8CunCy+2rsrmL3IpHCzHV8XZMutushMRRH1gZXavn6YVk2jrZ++dXUaWtqUKDvRcbfnY36m4qo5K6u7sPHXKPjOBq0efA2R2oG/j8GzG3GjWvW1f/4iRsIhhd6M6U9Z64uSh/oqcb1EXpshT3+4FKdT8aw1mwaVUS+HOmb46sYZWygKkx6INlDWAegvAOcRpP2TrwLfc6bb45VGEYEX0cOl6xuz2rO7GMFC7umeC0XTs3IFRJPhcE3YuxS7cmQikpaO6J3/QWjDCAfqU2Z1jK8IrCQfvwW7Dk8Pfh3pesbelS2uuXJC4WdLFa+Jm/cjpykNJV98oqyOCNJKWj58FjZuHMQCtsT5sRtKvL2UZe8KAm+RyVuiZRM1c9TmLgW9gu2F/njhnLyVUhI6ohgFKgL9nrc0BSUN4USftZU/I27SMfph0QQ/sryxUFe4o5Xpx41px0UvlE2qiUkRoLvRcvwKGILpueXe3L8atkbdbaX/zbXY1hFY0aJhoLqOjSHReABQuRYnnVn/v9BQ1+iOToth0HY1dEqMJTxjlxzxOcsIh2216dNvJgHFUAuUVhv/12jLD7z0zOTNw3n2LtVn5xgwGteQGUvz7I6Qyly7fhIM/0hCXi+IaKQC98vHI="
  app: udompoc-chatbot
