language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: PVrri2HNxSvruP93uh9mUHElCH3HcnilsDCcX5RpEWqMwwIZMtnbYo/nYDExqvYaDjE/8doJrYzSuJxsNx50ajYMhzibjRUnIDqyti4TuN/IDhJbRM7IekdYmaiXA5i1nmQj/MT4FZoT2kfmu3I2OWf8VULdNoji9HfSSpoWxaUg2uiiq97VDHirpivD3qg7Sy5YkZ4OwbB4NylX47KIDFm4isq7pIyb5D5jRu1jAqsPGR59aCeI1iv9Gz5L+EKDSN+yAL9xB6HRg9quQT2Q+hTSVciamfUtwJAuLOotV2dRYZp0H1X7ZqjP7G29DUqnr1xvyixPPfuv4cRuHNDfLpk9rOR9wN1x3RLtOtbERmE7Fqd6TgnyJG1HaPwDBNwkeuPVaML5TPZ0Y4G4Ei+6UQPn+ItpOGtLCXaztC9oFgSmIN2j1eVwRuIRPgeyoZfSpcJj91h+6s4340zpKmlnd1FNXZRNTCkQ0ZsNf148fQuYnPK86C5bRdMZJMpHLwg+wEQJV9rK3ZbanmV2tXtmRmRSU+fEfnqC0vu00kIruVZZ6yq6QVx2u1Q5qp9+w3/wVLjLRxwHyfF8e6DbAOGEQKusGC7Au3d+ecxZvvtDgumPe/vhUGZ+qYcQoQvp7a7auOtLgVC1N/kMfj2z9uY8FgljemCejsod5S8XytPtUns=
  app: udompoc-chatbot
